Bump required pytest version
Fixes internal error cause by flexmock:

```
INTERNALERROR>   File "/usr/lib/python2.7/site-packages/flexmock.py", line 1249, in call_runtest_hook
1129
INTERNALERROR>     teardown.duration = ret.duration
INTERNALERROR> AttributeError: 'CallInfo' object has no attribute 'duration'
```

flexmock 0.10.5 requires newer pytest, but doesn't properly specifies
min requirements

Signed-off-by: Martin Basti <mbasti@redhat.com>